import { createFileRoute } from "@tanstack/react-router";
import { Link } from "@tanstack/react-router";
import { LegalPage, LegalSection } from "@/components/legal-page";

const TITLE = "Terms & Conditions — Assignmate";
const DESCRIPTION =
  "The terms that govern your use of Assignmate, including accounts, acceptable use, AI-generated content, billing and subscriptions.";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: TITLE },
      { name: "description", content: DESCRIPTION },
      { property: "og:title", content: TITLE },
      { property: "og:description", content: DESCRIPTION },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
      { property: "og:url", content: "https://assignmateai.in/terms" },
    ],
    links: [{ rel: "canonical", href: "https://assignmateai.in/terms" }],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <LegalPage
      title="Terms & Conditions"
      intro="By creating an account or using Assignmate, you agree to these terms. Please read them carefully."
    >
      <LegalSection heading="Your account">
        <p>
          You are responsible for keeping your login credentials secure and for all activity that
          happens under your account. Accounts are personal and should not be shared.
        </p>
      </LegalSection>

      <LegalSection heading="Acceptable use">
        <p>
          Assignmate is a study and writing workspace. You agree not to use it to break the law,
          to upload content you have no right to use, or to attempt to disrupt, reverse engineer
          or overload the service.
        </p>
        <p>
          You are responsible for following the academic integrity rules of your school, college
          or university when using AI-assisted output.
        </p>
      </LegalSection>

      <LegalSection heading="AI-generated content">
        <p>
          Output is generated by AI models and can contain mistakes. You should review, verify and
          edit anything before submitting it. Assignmate does not guarantee accuracy, grades or
          any particular academic outcome.
        </p>
      </LegalSection>

      <LegalSection heading="Subscriptions and billing">
        <p>
          Paid plans are billed through Razorpay over a secure, encrypted checkout and are
          activated instantly after a successful payment. Plan limits, credits and renewal dates
          are shown in your dashboard.
        </p>
        <p>
          Subscription purchases are digital and are generally non-refundable once activated. How
          activation, failed activations and duplicate payments are handled is described in our{" "}
          <Link to="/subscription-policy" className="text-primary underline underline-offset-4">
            Subscription Policy
          </Link>
          , which forms part of these terms.
        </p>
      </LegalSection>

      <LegalSection heading="Service availability and changes">
        <p>
          We may update, add or remove features to improve the service. We may suspend accounts
          that violate these terms. Where reasonable, we will give notice of significant changes.
        </p>
      </LegalSection>

      <LegalSection heading="Contact">
        <p>
          Questions about these terms? Reach us through the{" "}
          <Link to="/contact" className="text-primary underline underline-offset-4">
            Contact Us
          </Link>{" "}
          page.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
